language: node_js
node_js: lts/*

before-install:
- cp src/config/config.local.ts src/config/config.ts

before_deploy:
- openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa

deploy:
  provider: script
  skip_cleanup: true
  script: ssh -oStrictHostKeyChecking=no $EVD_DEVICE_HOST 'bash ./deploy.sh'
  on:
    branch: master

env:
  global:
    secure: cLBWfpQCNkfDWo4l+ROggmJPLyhetu0Pz8VrQXL2LOrN9dnDuLjUSVLmGT8NE1Z2aA6zjoG3zAy9AwVYxSX51cWafcH/Eu/M7MR6HTf8tuSWTP3t9QjPOzhR5K6wurM6mI7fneBzQjhMGC6YbgODk1E5NiVshFlg0hIjTzEizCUvMg9/i/lfB0A/XZj3l75lz3djDdkJVTBczxclfboEFzjzidwUYjE/pOBJchft0bIZIRDtbZ5K+sdd3hP3zfP9j8LNFluBB3jWHnBRpXADbXyiZwrHx0PKkzxsFlX41u4+bTlxs/lgJ68F1bqFIpp9G1Xm5U+3m6TV+yAwBgANxuBmPNGg5GWFAp4qsekxn/ezvXTtY+zHfneQyvqwP2qao1TeBSmeTkBw4bY7LIRv1ot7kGH5JGrByiIquP1BtJqo7h+ZA7UvWEZs3gGGGBEzhsGOr3RaTUOdGgdHYizYEwTh7UU1SAFWC8rK1DcbdDZ29qvZoi3jcVPtSs/qfOL4CNJtHXqlfqaP1rbdSJzLqPRF8zxmTZAS9kKKzYjngTkXdHusEwVIujWFsNMd0L1IjoZQ9P4eUfjcMJmN5b7HQTih2E3sBQevLE0ezyXCysfl94wWVfKs8Fm9hXcUQ4BOYeuutuvlfAInqfRStIughqGPu7MQs0npPJULlnVyL6k=
